// Copy this file to src/config.js and paste your key. src/config.js is git-ignored.
// On GitHub Pages the file is generated by the deploy workflow from the
// GOOGLE_PLACES_API_KEY repository secret.
export const GOOGLE_PLACES_API_KEY = 'PASTE_YOUR_KEY_HERE';
